"""Initial migration

Revision ID: c3394035a72d
Revises: 
Create Date: 2024-12-20 01:23:31.788564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3394035a72d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID of the user owning the bot'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Name of the bot'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description of the bot'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp of creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last update'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bots_id'), 'bots', ['id'], unique=False)
    op.create_index(op.f('ix_bots_user_id'), 'bots', ['user_id'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False, comment='ID of the bot this block belongs to'),
    sa.Column('type', sa.String(length=255), nullable=False, comment="Type of the block (e.g., 'message', 'action')"),
    sa.Column('content', sa.JSON(), nullable=False, comment='Content of the block'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp of creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last update'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocks_bot_id'), 'blocks', ['bot_id'], unique=False)
    op.create_index(op.f('ix_blocks_id'), 'blocks', ['id'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_block_id', sa.Integer(), nullable=False, comment='ID of the source block'),
    sa.Column('target_block_id', sa.Integer(), nullable=False, comment='ID of the target block'),
    sa.Column('type', sa.String(length=255), nullable=False, comment="Type of the connection (e.g., 'default', 'conditional')"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp of creation'),
    sa.ForeignKeyConstraint(['source_block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    op.create_index(op.f('ix_connections_source_block_id'), 'connections', ['source_block_id'], unique=False)
    op.create_index(op.f('ix_connections_target_block_id'), 'connections', ['target_block_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connections_target_block_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_source_block_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_blocks_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_bot_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_bots_user_id'), table_name='bots')
    op.drop_index(op.f('ix_bots_id'), table_name='bots')
    op.drop_table('bots')
    # ### end Alembic commands ###
