# services\auth_service\docker-compose.override.yml
version: '3.7'
services:
  auth_service:
    build: .
    container_name: auth_service
    ports:
      - "8002:8002"
    env_file:
      - .env
    volumes:
      - ./:/app
    command: >
      uvicorn src.app:app --host 0.0.0.0 --port 8002 --reload
