"""Initial migration

Revision ID: 6abd97d11ba2
Revises: 53fdc82a0b1f
Create Date: 2024-12-22 01:39:55.168798

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6abd97d11ba2"
down_revision: Union[str, None] = "53fdc82a0b1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
