"""Initial migration

Revision ID: 80db8a0f880f
Revises: 
Create Date: 2024-12-22 01:11:58.228645

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80db8a0f880f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="ID пользователя, владеющего ботом",
        ),
        sa.Column(
            "name", sa.String(length=255), nullable=False, comment="Имя бота"
        ),
        sa.Column(
            "description", sa.Text(), nullable=True, comment="Описание бота"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Дата и время создания бота",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата и время последнего обновления бота",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bots_id"), "bots", ["id"], unique=False)
    op.create_index(op.f("ix_bots_user_id"), "bots", ["user_id"], unique=False)
    op.create_table(
        "metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "bot_id",
            sa.Integer(),
            nullable=False,
            comment="ID бота, к которому относятся метаданные",
        ),
        sa.Column(
            "metadata_key",
            sa.String(length=255),
            nullable=False,
            comment="Ключ метаданных (например, 'version', 'description')",
        ),
        sa.Column(
            "metadata_value",
            sa.Text(),
            nullable=False,
            comment="Значение метаданных (например, '1.0', 'My awesome bot')",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Дата и время создания метаданных",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата и время последнего обновления метаданных",
        ),
        sa.ForeignKeyConstraint(["bot_id"], ["bots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_metadata_bot_id"), "metadata", ["bot_id"], unique=False
    )
    op.create_index(op.f("ix_metadata_id"), "metadata", ["id"], unique=False)
    op.create_index(
        op.f("ix_metadata_metadata_key"),
        "metadata",
        ["metadata_key"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_metadata_metadata_key"), table_name="metadata")
    op.drop_index(op.f("ix_metadata_id"), table_name="metadata")
    op.drop_index(op.f("ix_metadata_bot_id"), table_name="metadata")
    op.drop_table("metadata")
    op.drop_index(op.f("ix_bots_user_id"), table_name="bots")
    op.drop_index(op.f("ix_bots_id"), table_name="bots")
    op.drop_table("bots")
    # ### end Alembic commands ###
