"""Initial migration

Revision ID: 53fdc82a0b1f
Revises: 80db8a0f880f
Create Date: 2024-12-22 01:34:34.633859

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "53fdc82a0b1f"
down_revision: Union[str, None] = "80db8a0f880f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
